// Code generated by "stringer -type=Satisfiable"; DO NOT EDIT

package smt

import "fmt"

const _Satisfiable_name = "SatUnsatUnknown"

var _Satisfiable_index = [...]uint8{0, 3, 8, 15}

func (i Satisfiable) String() string {
	if i < 0 || i >= Satisfiable(len(_Satisfiable_index)-1) {
		return fmt.Sprintf("Satisfiable(%d)", i)
	}
	return _Satisfiable_name[_Satisfiable_index[i]:_Satisfiable_index[i+1]]
}
